:doctitle:    A brief introduction to VA-PALS – Blog posts – VA-PALS – Projects – Staff – Vista Expertise Network

== A Brief Introduction to VA-PALS 

The https://www.va.gov/opa/pressrel/pressrelease.cfm?id=2942[VA{nbhy}PALS
Project] (VA-Partnership to increase Access to Lung Screening) is funded by a
generous grant from the
https://www.bms.com/about-us/responsibility/bristol-myers-squibb-foundation.html[Bristol-Myers
Squibb Foundation] and a grant from VA's https://www.ruralhealth.va.gov/[Office
of Rural Health] to extend the http://ielcap.com/[International Early Lung
Cancer Action Program] (I{nbhy}ELCAP) protocols to the VA health
system. I{nbhy}ELCAP, in turn, is intended to improve screening and treatment
protocols for early-stage lung cancers.

Determining the right people to screen at the right time is important in
providing the most benefit for the investment made. The I{nbhy}ELCAP protocol
is designed by international experts in lung cancer, radiology and related
fields who collaborate on development and continual updating of the
evidence. The I{nbhy}ELCAP investigators meet twice a year to refine these
methods, share their research, and update the protocol as needed.

An important part of the I{nbhy}ELCAP program is to also increase the
performance of the CT scanners themselves. This is accomplished through
consulting and quality-measurement programs provided and administered by
http://accumetra.com/[Accumetra]. Take a look at
http://accumetra.com/solutions/free-ct-image-quality-reports/[Accumetra's
Scotch tape program]. Very interesting stuff.

Radiologists are trained to better identify suspicious nodules in the low-dose
CT scans through education as well as by dual reading of scans with
radiologists who have experience in interpreting low-dose CT scans in the
context of a program of CT screening for lung cancer.  This can be done
remotely, so moving huge image files between facilities is an issue that is
being addressed by the VA{nbhy}PALS program.

Deciding what kind of treatment is most beneficial for each kind of cancer and
patient is important as well. The I{nbhy}ELCAP organization has been conducting
research on which treatment methods are optimal for early stage lung cancer.

Our part of this important project is to develop an extension of the VistA
software to mirror the capabilities of the ELCAP software and store the data
within VistA's existing architecture, so that VA care providers can integrate
the I{nbhy}ELCAP protocol in their existing workflows. After that, we'll be
working with the VA Nurse Navigators/Coordinators to improve the extension for
VA users, and with the ELCAP team to provide their reports within the VA
system. We will also be developing the capability for the VA ELCAP software to
work on its own and with other EMRs.

It's been very exciting to learn about the possibilities to save lives and
reduce pain and suffering through our work on this program. We look forward to
the coming years as we work on this project with VA and the OSEHRA community.

Linda Yaw +
Director of Operations +
Vista Expertise Network

