KBAPTIU ;ven/lgc - M2M data from another system ; 5/21/18 12:18pm
 ;;1.0;;**LOCAL**; APR 22, 2018
 ;
 ;K POO,DFN,TITLE,VDT,SUPPRESS,NOASF
 ;S DFN=718 
 ;S TITLE=5847
 ;S VDT=3180518.101013
 ;S POO(1202)=71 ; USER
 ;S POO(1301)=3180518.095123 ; REFERENCE DATE
 ;S POO(1205)=7 ; CLINICX
 ;S POO(1701)="" ;SUBJECT
 ;S SUPPRESS="7;3180518.095242;A"
 ;S NOASF=1 ; Do not commit
 ;
 ;D MAKE^TIUSRVP(.XDATA,DFN,TITLE,VDT,,,.POO,SUPPRESS,NOASF)
 ;
 ; Build a tiu and visit in Avicenna from larrypoo docker
EN(DFN) Q:'$G(DFN)
 D BLDTIU^KBAPTIU(.TIUIEN,DFN,5847)
 Q
 ; call into larrypoo docker and build tiu
 ; D BLDTIU^KBAPTIU(.TIUIEN,813,5847,71,7)
BLDTIU(TIUIEN,DFN,TITLE,USER,CLINIEN) ;
 N IP,PORT,ACCVER
 S PORT=$$GET^XPAR("SYS","SAMI PORT",,"Q")
 S IP=$$GET^XPAR("SYS","SAMI IP ADDRESS",,"Q")
 S:($G(IP)="") IP="127.0.0.1"
 Q:$G(IP)=""  Q:$G(PORT)=""
 S ACCVER=$$GET^XPAR("SYS","SAMI ACCVER",,"Q")
 Q:$G(ACCVER)=""  Q:'($L($G(ACCVER),";")=2)
 Q:'$G(DFN)  Q:'$G(TITLE)  Q:'$G(DUZ)
 Q:'$G(CLINIEN)
 K TIUIEN
 N SUPPRESS,VDT,NOASF
 S VDT=$$HTFM^XLFDT($H)
 S SUPPRESS=CLINIEN_";"_$$HTFM^XLFDT($H)_";A"
 S NOASF=1 ; Do not commit
 ;
 ;D MAKE^TIUSRVP(.TIUIEN,DFN,TITLE,VDT,,,.POO,SUPPRESS,NOASF)
 ;Q
 ;
 N CONNECT,DIVFLAG,XWBDIVS,DIVISION,CONTEXT,X,I
 S CONNECT=$$CONNECT^XWBM2MC(PORT,IP,ACCVER)
 Q:'($G(CONNECT)=1)
 S DIVFLAG=$$GETDIV^XWBM2MC("DIVISIONS")
 S XWBDIVS=0,DIVISION=$$SETDIV^XWBM2MC(XWBDIVS)
 S CONTEXT=$$SETCONTX^XWBM2MC("OR CPRS GUI CHART")
 K ^TMP("POO")
 ;
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=DFN
 S X=$$PARAM^XWBM2MC(1,$NA(^TMP("POO",$J)))
 ;
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=TITLE
 S X=$$PARAM^XWBM2MC(2,$NA(^TMP("POO",$J)))
 ;
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=VDT
 S X=$$PARAM^XWBM2MC(3,$NA(^TMP("POO",$J)))
 ;
 K ^TMP("MKTIU",$J)
 S ^TMP("MKTIU",$J,"TYPE")="ARRAY"
 S ^TMP("MKTIU",$J,"VALUE",1202)=USER
 S ^TMP("MKTIU",$J,"VALUE",1301)=$$HTFM^XLFDT($H) ; REFERENCE DATE
 S ^TMP("MKTIU",$J,"VALUE",1205)=CLINIEN ; CLINIC IEN IN ^SC
 S ^TMP("MKTIU",$J,"VALUE",1701)=""
 S ^TMP("POO",$J,"TYPE")="LIST"
 S X=$$PARAM^XWBM2MC(6,$NA(^TMP("MKTIU",$J)))
 ;
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=SUPPRESS
 S X=$$PARAM^XWBM2MC(7,$NA(^TMP("POO",$J)))
 ;
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=NOASF
 S X=$$PARAM^XWBM2MC(8,$NA(^TMP("POO",$J)))
 ;
 S CALL=$$CALLRPC^XWBM2MC("TIU CREATE RECORD","REQ",1)
 ;
 S CLOSE=$$CLOSE^XWBM2MC
 Q
 ;
 ; e.g.
 D SETTXT^KBAPTIU(.XDATA,20,9430,"34.212.101.84","SEPI9393;Pvul+9339")
SETTXT(XDATA,TIUIEN,TXTARR,PORT,IP,ACCVER) ;
 Q:'$G(TIUIEN)
 ;
 N CONNECT,DIVFLAG,XWBDIVS,DIVISION,CONTEXT,X,I,SUPPRESS
 S CONNECT=$$CONNECT^XWBM2MC(PORT,IP,ACCVER)
 Q:'($G(CONNECT)=1)
 S DIVFLAG=$$GETDIV^XWBM2MC("DIVISIONS")
 S XWBDIVS=0,DIVISION=$$SETDIV^XWBM2MC(XWBDIVS)
 S CONTEXT=$$SETCONTX^XWBM2MC("OR CPRS GUI CHART")
 S SUPPRESS=TIUIEN_";"_$$HTFM^XLFDT($H)_";A"
 ;
 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=TIUIEN
 S X=$$PARAM^XWBM2MC(1,$NA(^TMP("POO",$J)))
 ;
 K ^TMP("MKTIU",$J)
 S ^TMP("MKTIU",$J,"HEADER")=<1^1>
 S ^TMP("MKTIU",$J,"TEXT",1,0)="<First line of docment through M2M>"
 S ^TMP("MKTIU",$J,"TEXT",2,0)="<Second line of document through M2M>"
 S ^TMP("MKTIU",$J,"TEXT",3,0)="<Third line of document through M2M?"
 S ^TMP("POO",$J,"TYPE")="LIST"
 S X=$$PARAM^XWBM2MC(6,$NA(^TMP("MKTIU",$J)))
 ;
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=SUPPRESS
 S X=$$PARAM^XWBM2MC(7,$NA(^TMP("POO",$J)))
 ;
 S CALL=$$CALLRPC^XWBM2MC("TIU CREATE RECORD","REQ",1)
 ;
 S CLOSE=$$CLOSE^XWBM2MC
 Q
 ;
 ;
EOR ;Ene of routine KBAPTIU
