KBAPTIU ;;ven/lgc - M2M Broker to build TIU ; 8/21/18 9:52am
 ;;1.0;;**LOCAL**; APR 22, 2018
 ;
 ; VA-PALS will be using the Sam Habiel's [KBANSCAU] broker
 ;   to gather information from the server onto the VA-PALS
 ;   client and, to push TIU notes generated by the
 ;   VA-PALS forms onto the server.
 ; Using this broker between VistA instances requires
 ;   not only the IP and Port for the server be known,
 ;   but also, that the Access and Verify of the user
 ;   on the server be sent across as well.  This is
 ;   required as the user on the server must have the
 ;   necessary Context menu allowing use of the
 ;   Remote Procedure.
 ; The below parameters have been added to the client
 ;   VistA to prevent the necessity of hard coding
 ;   these values.
 ;   SAMI ACCVER  --- Accession/Verify code
 ;      for the default user
 ;   SAMI DEFAULT CLINIC IEN
 ;   SAMI DEFAULT PROVIDER DUZ
 ;   SAMI IP ADDRESS  --- IP address of server
 ;   SAMI NOTE TITLE PRINT NAME --- print name of the
 ;      default TIU note title to use
 ;   SAMI PORT --- broker port for server
 ; Note that the user selected must have active
 ;   credentials on both the Client and Server systems
 ;   and the following Broker context menus.
 ;      OR CPRS GUI CHART
 ;
 ; Temporary entry for VA-PALS testing
 ; Force TIU note TITLE, User, and Clinic
EN(DFN) Q:'$G(DFN)
 D BLDTIU^KBAPTIU(.TIUIEN,DFN,5847,71,7)
 Q
 ;
 ; Build a TIU and VISIT stubb
 ; Remote Procedure : TIU CREATE RECORD
 ; ENTER
 ;   TIUIEN  : variable by reference
 ;   DFN     : IEN into PATIENT [#2] file
 ;   TITLE   : TIU title IEN into TIU DOCUMENT DEFINITION [#8925.1]
 ;   USER    : DUZ of user generating TIU document
 ;   CLINIEN : IEN of clinic in HOSPITAL LOCATION [#44]
 ; RETURN
 ;   TIUIEN  : IEN of new TIU note. 0=failure
BLDTIU(TIUIEN,DFN,TITLE,USER,CLINIEN) ;
 I '$G(DFN) Q:$Q 0  Q
 I '$G(USER) Q:$Q 0  Q
 I '$G(TITLE) D  I '$G(TITLE) Q:$Q 0  Q
 . N TITPN S TITPN=$$GET^XPAR("SYS","SAMI NOTE TITLE PRINT NAME",,"Q")
 . S TITLE=$O(^TIU(8925.1,"D",TITPN,0))
 I '$G(CLINIEN) D  I '$G(CLINIEN) Q:$Q 0  Q
 . S CLINIEN=$$GET^XPAR("SYS","SAMI DEFAULT CLINIC IEN",,"Q")
 Q:'$G(CLINIEN)
 K TIUIEN
 N SUPPRESS,VDT,NOASF,VSTR
 S VSTR=CLINIEN_";"_VDT_";A"
 S SUPPRESS=1
 S NOASF=1 ; Do not commit
 ;
 N CNTXT,RMPRC,CONSOLE,CNTNOPEN,XARRAY
 S CNTXT="OR CPRS GUI CHART"
 S RMPRC="TIU CREATE RECORD"
 S (CONSOLE,CNTNOPEN)=0
 ;
 S XARRAY(1)=DFN
 S XARRAY(2)=TITLE
 S XARRAY(3)=""
 S XARRAY(4)=""
 S XARRAY(5)=""
 ;
 N POO
 S POO(1202)=USER
 S POO(1301)=$$HTFM^XLFDT($H) ; REFERENCE DATE
 S POO(1205)=CLINIEN
 S POO(1701)=""
 S XARRAY(6)="@POO"
 ;
 S XARRAY(7)=VSTR
 S XARRAY(8)=SUPPRESS
 D M2M^KBAPM2M(.XDATA,CNTXT,RMPRC,CONSOLE,CNTNOPEN,.XARRAY)
 Q:$Q +$G(XDATA)  Q
 ;
 ;
 ; Build a tiu addendum
ENAD(TIUIEN,USERDUZ) Q:'$G(TIUIEN)
 D BLDTIUA^KBAPTIU(.TIUADIEN,TIUIEN,USERDUZ)
 Q
 ; call into larrypoo docker and build tiu
 ; D BLDTIUA^KBAPTIU(.TIUIEN,22,71)
BLDTIUA(TIUAIEN,TIUIEN,USERDUZ) ;
 N IP,PORT,ACCVER
 S PORT=$$GET^XPAR("SYS","SAMI PORT",,"Q")
 S IP=$$GET^XPAR("SYS","SAMI IP ADDRESS",,"Q")
 S:($G(IP)="") IP="127.0.0.1"
 Q:$G(IP)=""  Q:$G(PORT)=""
 S ACCVER=$$GET^XPAR("SYS","SAMI ACCVER",,"Q")
 Q:$G(ACCVER)=""  Q:'($L($G(ACCVER),";")=2)
 Q:'$G(TIUIEN)  Q:'$G(USERDUZ)
 ;
 K TIUAIEN
 N VDT,NOASF
 S VDT=$$HTFM^XLFDT($H)
 S NOASF=1 ; Do not commit
 ;
 ;D MAKEADD^TIUSRVP(.TIUIEN,.POO,NOASF)
 ;Q
 ;
 N CONNECT,DIVFLAG,XWBDIVS,DIVISION,CONTEXT,X,I
 S CONNECT=$$CONNECT^XWBM2MC(PORT,IP,ACCVER)
 Q:'($G(CONNECT)=1)
 S DIVFLAG=$$GETDIV^XWBM2MC("DIVISIONS")
 S XWBDIVS=0,DIVISION=$$SETDIV^XWBM2MC(XWBDIVS)
 S CONTEXT=$$SETCONTX^XWBM2MC("OR CPRS GUI CHART")
 K ^TMP("POO")
 ;
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=TIUIEN
 S X=$$PARAM^XWBM2MC(1,$NA(^TMP("POO",$J)))
 ;
 K ^TMP("MKTIU",$J)
 S ^TMP("MKTIU",$J,"TYPE")="ARRAY"
 S ^TMP("MKTIU",$J,"VALUE",1202)=USERDUZ
 S ^TMP("MKTIU",$J,"VALUE",1301)=$$HTFM^XLFDT($H) ; REFERENCE DATE
 S X=$$PARAM^XWBM2MC(2,$NA(^TMP("MKTIU",$J)))
 ;
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=NOASF
 S X=$$PARAM^XWBM2MC(8,$NA(^TMP("POO",$J)))
 ;
 S CALL=$$CALLRPC^XWBM2MC("TIU CREATE ADDENDUM RECORD","REQ",1)
 ;
 S CLOSE=$$CLOSE^XWBM2MC
 Q
 ;
 ;
 ; Additional Signers
ENSNRS(TIUIEN) Q:'$G(TIUIEN)
 N TIULIST
 S TIULIST(1)="72^King,Matt"
 S TIULIST(2)="64^Smith,Mary"
 D ADDSGNR^KBAPTIU(.TIUADIEN,TIUIEN,.TIULIST)
 Q
 ; call into larrypoo docker and build tiu
 ;
ADDSGNR(XDATA,TIUIEN,TIULIST) ;
 N IP,PORT,ACCVER
 S PORT=$$GET^XPAR("SYS","SAMI PORT",,"Q")
 S IP=$$GET^XPAR("SYS","SAMI IP ADDRESS",,"Q")
 S:($G(IP)="") IP="127.0.0.1"
 Q:$G(IP)=""  Q:$G(PORT)=""
 S ACCVER=$$GET^XPAR("SYS","SAMI ACCVER",,"Q")
 Q:$G(ACCVER)=""  Q:'($L($G(ACCVER),";")=2)
 Q:'$G(TIUIEN)  Q:'$D(TIULIST)
 ;
 K XDATA
 ;
 ;D IDSIGNRS^TIULX(.XDATA,TIUIEN,.TIULIST)
 ;Q
 ;
 N CONNECT,DIVFLAG,XWBDIVS,DIVISION,CONTEXT,X,I
 S CONNECT=$$CONNECT^XWBM2MC(PORT,IP,ACCVER)
 Q:'($G(CONNECT)=1)
 S DIVFLAG=$$GETDIV^XWBM2MC("DIVISIONS")
 S XWBDIVS=0,DIVISION=$$SETDIV^XWBM2MC(XWBDIVS)
 S CONTEXT=$$SETCONTX^XWBM2MC("OR CPRS GUI CHART")
 ;
 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=TIUIEN
 S X=$$PARAM^XWBM2MC(1,$NA(^TMP("POO",$J)))
 ;
 K ^TMP("TIULIST",$J)
 S ^TMP("TIULIST",$J,"TYPE")="ARRAY"
 S ^TMP("TIULIST",$J,"VALUE",1)="72^King,Matt"
 S ^TMP("TIULIST",$J,"VALUE",2)="64^Smith,Mary"
 S X=$$PARAM^XWBM2MC(2,$NA(^TMP("TIULIST",$J)))
 ;
 S CALL=$$CALLRPC^XWBM2MC("TIU UPDATE ADDITIONAL SIGNERS","REQ",1)
 ;
 S CLOSE=$$CLOSE^XWBM2MC
 Q
 ;
 ; e.g.
 ;D SETTEXT^TIUSRVPT(.SUCCESS,23,.TIUX,SUPPRESS)
 ; *** Temporary test entry point ***
ENST(TIUIEN) Q:'$G(TIUIEN)
 D SETTEXT^KBAPTIU(.XDATA,TIUIEN)
 Q
 ;
SETTEXT(XDATA,TIUIEN) ;
 Q:'$G(TIUIEN)
 ;
 N CONNECT,DIVFLAG,XWBDIVS,DIVISION,CONTEXT,X,I,SUPPRESS
 N IP,PORT,ACCVER
 S PORT=$$GET^XPAR("SYS","SAMI PORT",,"Q")
 S IP=$$GET^XPAR("SYS","SAMI IP ADDRESS",,"Q")
 S:($G(IP)="") IP="127.0.0.1"
 Q:$G(IP)=""  Q:$G(PORT)=""
 S ACCVER=$$GET^XPAR("SYS","SAMI ACCVER",,"Q")
 Q:$G(ACCVER)=""  Q:'($L($G(ACCVER),";")=2)
 S CONNECT=$$CONNECT^XWBM2MC(PORT,IP,ACCVER)
 Q:'($G(CONNECT)=1)
 S DIVFLAG=$$GETDIV^XWBM2MC("DIVISIONS")
 S XWBDIVS=0,DIVISION=$$SETDIV^XWBM2MC(XWBDIVS)
 S CONTEXT=$$SETCONTX^XWBM2MC("OR CPRS GUI CHART")
 S SUPPRESS=0
 ;
ST1 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=TIUIEN
 S X=$$PARAM^XWBM2MC(1,$NA(^TMP("POO",$J)))
 ;
ST2 K ^TMP("TIUX")
 ;
 S ^TMP("TIUX",$J,"TYPE")="ARRAY"
 ;
 ; Results in the below array
 ;   XWBP2("HDR")=1^1
 ;   XWBP2("{TEXT,1,0")=Current cigarette smoker:
 ;   XWBP2("{TEXT,2,0")=    # of years: 15
 ;    NOTE: the "{" forces FIXSS^MXMLPRSE on the server
 S ^TMP("TIUX",$J,"VALUE","HDR")="1^1"
 S ^TMP("TIUX",$J,"VALUE","{TEXT,1,0")="Current cigarette smoker:"
 S ^TMP("TIUX",$J,"VALUE","{TEXT,2,0")="  How many years has the patien smoked? "
 S ^TMP("TIUX",$J,"VALUE","{TEXT,3,0")="    # of years: 15"
 S ^TMP("TIUX",$J,"VALUE","{TEXT,4,0")="  Average number of packs/day over the entire time patient smoked: "
 S ^TMP("TIUX",$J,"VALUE","{TEXT,5,0")="    Packs/day: 1.0"
 S ^TMP("TIUX",$J,"VALUE","{TEXT,6,0")=""
 S ^TMP("TIUX",$J,"VALUE","{TEXT,7,0")="  No clinical exclusions, patient is a current candidate for lung cancer"
 S ^TMP("TIUX",$J,"VALUE","{TEXT,8,0")="  screening."
 S ^TMP("TIUX",$J,"VALUE","{TEXT,9,0")="      Patient agrees to lung cancer screening.  Lung cancer screening"
 S ^TMP("TIUX",$J,"VALUE","{TEXT,10,0")="      information provided and low dose CT will be ordered."
 ;
 S X=$$PARAM^XWBM2MC(2,$NA(^TMP("TIUX",$J)))
 ;
ST3 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=SUPPRESS
 S X=$$PARAM^XWBM2MC(3,$NA(^TMP("POO",$J)))
 ;
CALLSTXT S CALL=$$CALLRPC^XWBM2MC("TIU SET DOCUMENT TEXT","REQ",1)
 ;
 S CLOSE=$$CLOSE^XWBM2MC
 Q
 ;
 ;
 ; e.g.
 ;D UPDATE^TIUSRVP(.SUCCESS,23,.TIUX,SUPPRESS)
 ; *** Temporary test entry point ***
ENUR S TIUIEN=23
 D UPDTREC^KBAPTIU(.XDATA,TIUIEN)
 Q
 ;
UPDTREC(XDATA,TIUIEN) ;
 Q:'$G(TIUIEN)
 ;
 N CONNECT,DIVFLAG,XWBDIVS,DIVISION,CONTEXT,X,I,SUPPRESS
 N IP,PORT,ACCVER
 S PORT=$$GET^XPAR("SYS","SAMI PORT",,"Q")
 S IP=$$GET^XPAR("SYS","SAMI IP ADDRESS",,"Q")
 S:($G(IP)="") IP="127.0.0.1"
 Q:$G(IP)=""  Q:$G(PORT)=""
 S ACCVER=$$GET^XPAR("SYS","SAMI ACCVER",,"Q")
 Q:$G(ACCVER)=""  Q:'($L($G(ACCVER),";")=2)
 S CONNECT=$$CONNECT^XWBM2MC(PORT,IP,ACCVER)
 Q:'($G(CONNECT)=1)
 S DIVFLAG=$$GETDIV^XWBM2MC("DIVISIONS")
 S XWBDIVS=0,DIVISION=$$SETDIV^XWBM2MC(XWBDIVS)
 S CONTEXT=$$SETCONTX^XWBM2MC("OR CPRS GUI CHART")
 S SUPPRESS=0
 ;
 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=TIUIEN
 S X=$$PARAM^XWBM2MC(1,$NA(^TMP("POO",$J)))
 ;
 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="ARRAY"
 S ^TMP("POO",$J,"VALUE","TEXT",1,0)="Current cigarette smoker:"
 S ^TMP("POO",$J,"VALUE","TEXT",2,0)="  How many years has the patient smoked? "
 S ^TMP("POO",$J,"VALUE","TEXT",3,0)="    # of years: 15"
 S ^TMP("POO",$J,"VALUE","TEXT",4,0)="  Average number of packs/day over the entire time patient smoked: "
 S ^TMP("POO",$J,"VALUE","TEXT",5,0)="    Packs/day: 1.0"
 S ^TMP("POO",$J,"VALUE","TEXT",6,0)=""
 S ^TMP("POO",$J,"VALUE","TEXT",7,0)="  No clinical exclusions, patient is a current candidate for lung cancer"
 S ^TMP("POO",$J,"VALUE","TEXT",8,0)="  screening."
 S ^TMP("POO",$J,"VALUE","TEXT",9,0)="      Patient agrees to lung cancer screening.  Lung cancer screening"
 S ^TMP("POO",$J,"VALUE","TEXT",10,0)="      information provided and low dose CT will be ordered."
 S X=$$PARAM^XWBM2MC(2,$NA(^TMP("POO",$J)))
 ;
 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")=SUPPRESS
 S X=$$PARAM^XWBM2MC(3,$NA(^TMP("POO",$J)))
 ;
CALLUR S CALL=$$CALLRPC^XWBM2MC("TIU UPDATE RECORD","REQ",1)
 ;
 S CLOSE=$$CLOSE^XWBM2MC
 Q
 ;
 ;
 ;
ENCTR(VSTDATE) ;
 ; *** Temporary test entry point ***
 D BLDENCTR^KBAPTIU(.XDATA,VSTDATE)
 Q
 ;
BLDENCTR(XDATA,VSTDATE) ;
 Q:'$G(VSTDATE)
 ;
 N CONNECT,DIVFLAG,XWBDIVS,DIVISION,CONTEXT,X,I,SUPPRESS
 N IP,PORT,ACCVER
 S PORT=$$GET^XPAR("SYS","SAMI PORT",,"Q")
 S IP=$$GET^XPAR("SYS","SAMI IP ADDRESS",,"Q")
 S:($G(IP)="") IP="127.0.0.1"
 Q:$G(IP)=""  Q:$G(PORT)=""
 S ACCVER=$$GET^XPAR("SYS","SAMI ACCVER",,"Q")
 Q:$G(ACCVER)=""  Q:'($L($G(ACCVER),";")=2)
 S CONNECT=$$CONNECT^XWBM2MC(PORT,IP,ACCVER)
 Q:'($G(CONNECT)=1)
 S DIVFLAG=$$GETDIV^XWBM2MC("DIVISIONS")
 S XWBDIVS=0,DIVISION=$$SETDIV^XWBM2MC(XWBDIVS)
 S CONTEXT=$$SETCONTX^XWBM2MC("OR CPRS GUI CHART")
 S SUPPRESS=0
 ;
ENCTR1 K ^TMP("POO")
 ;
 S ^TMP("POO",$J,"TYPE")="ARRAY"
 ;
 S ^TMP("POO",$J,"VALUE",1)="HDR^0^^7;3180705.130554;A"
 S ^TMP("POO",$J,"VALUE",2)="VST^DT^3180705.130554"
 S ^TMP("POO",$J,"VALUE",3)="VST^PT^646"
 S ^TMP("POO",$J,"VALUE",4)="VST^HL^7"
 S ^TMP("POO",$J,"VALUE",5)="VST^VC^A"
 S ^TMP("POO",$J,"VALUE",6)="PRV^71^^^CARLSON,LARRY G^1"
 S ^TMP("POO",$J,"VALUE",7)="POV+^F17.210^COUNSELING AND SCREENING^Nicotine dependence, cigarettes, uncomplicated^1^^0^^^1"
 S ^TMP("POO",$J,"VALUE",8)="COM^1^@"
 S ^TMP("POO",$J,"VALUE",9)="HF+^619713^LUNG SCREENING HF^LCS AGREES TO BE SCREENED^@^^^^^2^"
 S ^TMP("POO",$J,"VALUE",10)="COM^2^@"
 S ^TMP("POO",$J,"VALUE",11)="HF+^647046^LUNG SCREENING HF^LCS CHEST CT PREVIOUSLY^@^^^^^3^"
 S ^TMP("POO",$J,"VALUE",12)="COM^3^@"
 S ^TMP("POO",$J,"VALUE",13)="HF+^647085^LUNG SCREENING HF^LCS NO EXCLUSIONS^@^^^^^4^"
 S ^TMP("POO",$J,"VALUE",14)="COM^4^@"
 S ^TMP("POO",$J,"VALUE",15)="CPT+^99203^NEW PATIENT^Intermediate Exam  26-35 Min^1^71^^^0^5^"
 S ^TMP("POO",$J,"VALUE",16)="COM^5^@"
 S X=$$PARAM^XWBM2MC(1,$NA(^TMP("POO",$J)))
 ;
ENCTR2 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")="0"
 S X=$$PARAM^XWBM2MC(3,$NA(^TMP("POO",$J)))
 ;
ENCTR3 K ^TMP("POO")
 S ^TMP("POO",$J,"TYPE")="STRING"
 S ^TMP("POO",$J,"VALUE")="7"
 S X=$$PARAM^XWBM2MC(3,$NA(^TMP("POO",$J)))
 ;
CALLENCT S CALL=$$CALLRPC^XWBM2MC("ORWPCE SAVE","REQ",1)
 ;
 S CLOSE=$$CLOSE^XWBM2MC
 Q
 ;
TEST(DFN) ; Q:'$G(DFN)
 K POO
 S DFN=519
 S TIUX(1202)=71 ; user
 S TIUX(1301)=$$HTFM^XLFDT($H) ; reference date
 S TIUX(1205)=7 ; clinic ien in file 44
 S TIUX(1701)="" ; subject of tiue
 S TITLE=5847
 S CLINIEN=7
 S VSTR="7;3180705.110403;A"
 S SUPPRESS=1
 S NOASF=1
 D MAKE^TIUSRVP(.POO,DFN,TITLE,,,,.TIUX,VSTR,SUPPRESS)
 ZWR POO
 Q
 ;
DELTIU(TIUDA,VSTR,DFN) ;
 Q:'$G(TIUDA)  Q:'$G(DFN)  Q:'$G(VSTR)
 ; First delete the TIU note
 K POO
 D DELETE^TIUSRVP(.POO,TIUDA)
 W !,$G(POO)
 ; Now delete the associated PCE record
 ; VSTR = e.g. 7;3180705.091846;A
 K POO
 D DELETE^ORWPCE(.POO,VSTR,DFN)
 W !,$G(POO)
 Q
 ;
EOR ;End of routine KBAPTIU
