SAMIUTVS ;;ven/arc/lgc - UNIT TEST for SAMIVSTS ; 12/27/18 10:02am
 ;;18.0;SAMI;;
 ;
 ; VA-PALS will be using Sam Habiel's [KBANSCAU] broker
 ;   to pull information from the VA server into the
 ;   VA-PALS client and, to push TIU notes generated by
 ;   VA-PALS forms onto the VA server.
 ; Using this broker between VistA instances requires
 ;   not only the IP and Port for the server be known,
 ;   but also, that the Access and Verify of the user
 ;   on the server be sent across as well.  This is
 ;   required as the user on the server must have the
 ;   necessary Context menu(s) allowing use of the
 ;   Remote Procedure(s).
 ; Six parameters have been added to the client
 ;   VistA to prevent the necessity of hard coding
 ;   certain values and to allow for default values for others.
 ;   SAMI PORT
 ;   SAMI IP ADDRESS
 ;   SAMI ACCVER
 ;   SAMI DEFAULT PROVIDER
 ;   SAMI DEFAULT STATION NUMBER
 ;   SAMI TIU NOTE PRINT NAME
 ;   SAMI DEFAULT CLINIC IEN
 ;   SAMI SYSTEM TEST PATIENT DFN
 ; Note that the user selected must have active
 ;   credentials on both the Client and Server systems
 ;   and the following Broker context menu.
 ;      OR CPRS GUI CHART
 ;
 ; @section 0 primary development
 ;
 ; @routine-credits
 ; @primary-dev: Larry Carlson (lgc)
 ;  larry@fiscientific.com
 ; @primary-dev-org: Vista Expertise Network (ven)
 ;  http://vistaexpertise.net
 ; @copyright: 2012/2018, ven, all rights reserved
 ; @license: Apache 2.0
 ;  https://www.apache.org/licenses/LICENSE-2.0.html
 ;
 ; @application: SAMI
 ; @version: 18.0
 ; @patch-list: none yet
 ;
 ; @sac-exemption
 ;  sac 2.2.8 Vendor specific subroutines may not be called directly
 ;   except by Kernel, Mailman, & VA Fileman.
 ;  sac 2.3.3.2 No VistA package may use the following intrinsic
 ;   (system) variables unless they are accessed using Kernel or VA
 ;   FileMan supported references: $D[EVICE], $I[O], $K[EY],
 ;   $P[RINCIPAL], $ROLES, $ST[ACK], $SY[STEM], $Z*.
 ;   (Exemptions: Kernel & VA Fileman)
 ;  sac 2.9.1: Application software must use documented Kernel
 ;   supported references to perform all platform specific functions.
 ;   (Exemptions: Kernel & VA Fileman)
 ;  ============== UNIT TESTS ======================
 ;  NOTE: Unit tests will pull data using the local
 ;       client VistA files rather than risk degrading
 ;       large datasets in use.  NEVERTHELESS, it is
 ;       recommended that UNIT TESTS be run when
 ;       VA-PALS is not in use as some Graphstore globals
 ;       are temporarily moved while testing is running.
 ;
 ; @to-do
 ;
 ; @section 1 code
 ;
START I $T(^%ut)="" W !,"*** UNIT TEST NOT INSTALLED ***" Q
 D EN^%ut($T(+0),2)
 Q
 ;
STARTUP N utsuccess
 Q
 ;
SHUTDOWN ; ZEXCEPT: utsuccess
 K utsuccess
 Q
 ;
UTMGPH ; @TEST - Test making 'patient-lookup' Graphstore
 I '$D(^KBAP("ALLPTS")) D  Q
 .  D FAIL^%ut("^KBAP(""ALLPTS"") must exist for TESTING")
 ;
 D MKGPH^SAMIVSTS ; Rebuild 'patient-lookup' Graphstore
 ; Check that the Graphstore was built
 n ptlkup s ptlkup="^%wd(17.040801,""B"",""patient-lookup"")"
 n si s si=$O(@ptlkup@(0))
 I '$G(si) D  Q
 . D FAIL^%ut("MKGPH entry did not build 'patient-lookup' Graphstore")
 ;
 n node,snode,root,gien,dfn,PtData
 ;
 ;s root=$$setroot^%wd("patient-lookup")
 s root=$$SETROOT^SAMIVSTS("patient-lookup")
 ;
 S node=$NA(^KBAP("ALLPTS")),snode=$P(node,")")
 S utsuccess=1
 F  S node=$Q(@node) Q:node'[snode  D  Q:'utsuccess
 . S PtData=@node
 . S dfn=$P(PtData,"^",12)
 . s gien=$O(@root@("dfn",dfn,0))
 . I '$G(gien) S utsuccess=0 Q
 .;
 .; Now compare the entries in this Graphstore node with
 .;  the information in the respective ^KBAP("ALLPTS" node
 . I '$O(@root@("last5",$P(PtData,"^",9),0)) S utsuccess=0 Q
 . I '$L($P(PtData,"^")) S utsuccess=0 Q
 . I '$O(@root@("name",$P(PtData,"^"),0)) S utsuccess=0 Q
 . I '$L($P(PtData,"^",4)) S utsuccess=0 Q
 . I '$O(@root@("name",$P(PtData,"^",4),0)) S utsuccess=0 Q
 . I '$O(@root@("saminame",$P(PtData,"^",4),0)) S utsuccess=0 Q
 ;
 I 'utsuccess D  Q
 . D FAIL^%ut("'patient-lookup' Graphstore incorrectly built")
 D CHKEQ^%ut(utsuccess,1,"Testing Complete Graphstore build  FAILED!")
 Q
 ;
UTAPTS ; @TEST - Test pulling patient data through broker
 K ^KBAP("ALLPTS UNITTEST")
 D ALLPTS1^SAMIVSTS("ALLPTS UNITTEST")
 ;                in file 2         in ALLPTS
 ;  NAME            piece 1          piece 1
 ;  sex             piece 2          piece 6
 ;  birthdate       piece 3 fmdt     piece 10 (yyyymmdd)
 ;
 ; Pull NAME from file 2 B cross
 ;   Get NAME,sex,birthdate,build last5
 ; Pull entry in Graphstore using last5
 ;   Knowing gien get NAME,sex,birthdate
 ; Compare
 N name2,sex2,dob2,last52,dfn2
 N node2,nodeG,gien
 ;n root s root=$$setroot^%wd("patient-lookup")
 n root s root=$$SETROOT^SAMIVSTS("patient-lookup")
 S utsuccess=1
 S dfn2=0
 f  s dfn2=$O(^DPT(dfn2)) Q:'dfn2  D  Q:'utsuccess
 . s node2=$G(^DPT(dfn2,0))
 . s name2=$P(node2,"^")
 . s sex2=$$UP^XLFSTR($E($P(node2,"^",2)))
 . s dob2=$$FMTHL7^XLFDT($P(node2,"^",3))
 . s dob2=$E(dob2,1,4)_"-"_$E(dob2,5,6)_"-"_$E(dob2,7,8)
 . s gien=$O(@root@("dfn",dfn2,0))
 . s last52=$$UP^XLFSTR($E(name2))_$E($P(node2,"^",9),6,9)
 . I '$G(gien) S utsuccess=0 Q
 . I '$D(@root@("name",name2,gien)) S utsuccess=0 Q
 . I '($P($G(@root@(gien,"gender")),"^")=sex2) D  Q
 .. S utsuccess=0
 . I '$D(@root@("last5",last52,gien)) S utsuccess=0 Q
 . I '($G(@root@(gien,"sbdob"))=dob2) S utsuccess=0 Q
 K ^KBAP("ALLPTS UNITTEST")
 I 'utsuccess D  Q
 . D FAIL^%ut("KBAP(""ALLPTS UNITTEST"") incorrectly built")
 D CHKEQ^%ut(utsuccess,1,"Testing pulling patients through broker FAILED!")
 Q
 ;
UTPRVDS ; @TEST - Pulling Providers through the broker
 K ^KBAP("UNIT TEST PROVIDERS")
 ;n root s root=$$setroot^%wd("providers")
 n root s root=$$SETROOT^SAMIVSTS("providers")
 m ^KBAP("UNIT TEST PROVIDERS")=@root
 S utsuccess=1
 N SAMIpvds
 S SAMIpvds=$$PRVDRS^SAMIVSTS
 I '$G(SAMIpvds) D  Q
 . M @root=^KBAP("UNIT TEST PROVIDERS") K ^KBAP("UNIT TEST PROVIDERS")
 . D FAIL^%ut("No providers pulled through broker")
 n ien,duzG,nameG
 f ien=1:1:$G(SAMIpvds) D  Q:'utsuccess
 . s duzG=@root@(ien,"duz")
 . s nameG=@root@(ien,"name")
 . I '$D(^XUSEC("PROVIDER",duzG)) S utsuccess=0 Q
 .; I '$$ACTIVE^XUSER(duzG) S utsuccess=0 Q
 . I '($$UP^XLFSTR(nameG))=($$UP^XLFSTR($P($G(^VA(200,duzG,0)),"^"))) D  Q
 .. S utsuccess=0
 m @root=^KBAP("UNIT TEST PROVIDERS") K ^KBAP("UNIT TEST PROVIDERS")
 D CHKEQ^%ut(utsuccess,1,"Testing pulling Providers through broker FAILED!")
 Q
 ;
UTRMDRS ; @TEST - Pulling Reminders through the broker
 K ^KBAP("UNIT TEST REMINDERS")
 ;n root s root=$$setroot^%wd("reminders")
 n root s root=$$SETROOT^SAMIVSTS("reminders")
 m ^KBAP("UNIT TEST REMINDERS")=@root
 S utsuccess=1
 N SAMIreminders
 S SAMIreminders=$$RMDRS^SAMIVSTS
 I '$G(SAMIreminders) D  Q
 . M @root=^KBAP("UNIT TEST REMINDERS")
 . K ^KBAP("UNIT TEST REMINDERS")
 . D FAIL^%ut("No reminders pulled through broker")
 n ienV,ienG,nameG,pnameG,typeG
 f ienG=1:1:$G(SAMIreminders) D  Q:'utsuccess
 . s nameG=@root@(ienG,"name") ; Mixed case
 . s pnameG=@root@(ienG,"printname") ; All caps
 . s typeG=@root@(ienG,"type")
 . s ienV=@root@(ienG,"ien")
 . I typeG="R" D  Q:'utsuccess
 .. I '$D(^PXD(811.9,"B",pnameG,ienV)) S utsuccess=0 Q
 .. I '$D(^PXD(811.9,"D",nameG,ienV)) S utsuccess=0 Q
 . I typeG="C" D  Q:'utsuccess
 .. I '($G(^PXRMD(811.7,ienV,0))=nameG) S utsuccess=0 Q
 m @root=^KBAP("UNIT TEST REMINDERS")
 K ^KBAP("UNIT TEST REMINDERS")
 D CHKEQ^%ut(utsuccess,1,"Testing pulling Reminders through broker FAILED!")
 Q
 ;
 ;
UTCLNC ; @TEST - Pulling Clinics through the broker
 K ^KBAP("UNIT TEST CLINICS")
 ;n root s root=$$setroot^%wd("clinics")
 n root s root=$$SETROOT^SAMIVSTS("clinics")
 m ^KBAP("UNIT TEST CLINICS")=@root
 S utsuccess=1
 N SAMIclnc
 S SAMIclnc=$$CLINICS^SAMIVSTS
 I '$G(SAMIclnc) D  Q
 . M @root=^KBAP("UNIT TEST CLINICS")
 . K ^KBAP("UNIT TEST CLINICS")
 . D FAIL^%ut("No clinics pulled through broker")
 n ienG,ienV,nameG
 f ienG=1:1:$G(SAMIclnc) D  Q:'utsuccess
 . s nameG=@root@(ienG,"name")
 . s ienV=@root@(ienG,"ien")
 . I '$D(^SC("B",nameG,ienV)) S utsuccess=0 Q
 m @root=^KBAP("UNIT TEST CLINICS")
 K ^KBAP("UNIT TEST CLINICS")
 D CHKEQ^%ut(utsuccess,1,"Testing pulling Clinics through broker FAILED!")
 Q
 ;
 ;
UTHF ; @TEST - Pulling Health Factors through the broker
 K ^KBAP("UNIT TEST HEALTH FACTORS")
 ;n root s root=$$setroot^%wd("health-factors")
 n root s root=$$SETROOT^SAMIVSTS("health-factors")
 m ^KBAP("UNIT TEST HEALTH FACTORS")=@root
 S utsuccess=1
 N SAMIhf
 S SAMIhf=$$HLTHFCT^SAMIVSTS
 I '$G(SAMIhf) D  Q
 . M @root=^KBAP("UNIT TEST HEALTH FACTORS")
 . K ^KBAP("UNIT TEST HEALTH FACTORS")
 . D FAIL^%ut("No health factors pulled through broker")
 n ienV,ienG,nameG
 f ienG=1:1:$G(SAMIhf) D  Q:'utsuccess
 . s nameG=@root@(ienG,"name")
 . s ienV=@root@(ienG,"ien")
 . I '($P($G(^AUTTHF(ienV,0)),"^")=nameG) S utsuccess=0 Q
 m @root=^KBAP("UNIT TEST HEALTH FACTORS")
 K ^KBAP("UNIT TEST HEALTH FACTORS")
 D CHKEQ^%ut(utsuccess,1,"Testing pulling Health Factors through broker FAILED!")
 Q
 ;
UTCLRG ; @TEST - Clear a Graphstore of entries
 ;n root s root=$$setroot^%wd("providers")
 n root s root=$$SETROOT^SAMIVSTS("providers")
 K ^KBAP("UNIT TEST CLRGRPH") M ^KBAP("UNIT TEST CLRGRPH")=@root
 n cnt s cnt=$O(@root@("A"),-1)
 I 'cnt D  Q
 . D FAIL^%ut("No 'providers found' entry")
 s cnt=$$CLRGRPS^SAMIVSTS("providers"),cnt=$O(@root@("A"),-1)
 M @root=^KBAP("UNIT TEST CLRGRPH") K ^KBAP("UNIT TEST CLRGRPH")
 D CHKEQ^%ut(cnt,0,"Clear Graphstore FAILED!")
 Q
EOR ; End of Routine SAMIUTVS
