:mastimg: project-va-pals
:mastcaption: va-pals
:mastdesc: Project: VA-PALS
:doctitle: VAPALS-ELCAP – Projects – Vista Expertise Network
:description: The VAPALS-ELCAP project page: Increasing access to safe and effective lung-screening programs that save lives.
:addkeywords: cancer, lung cancer, screening, early detection, cancer detection, VAPALS, ELCAP, I-ELCAP, VA-PALS, SAMI routines, web application in M

[role="h1 center"]
VAPALS-ELCAP

__**Mission:** To increase access to safe and effective lung-screening programs
that save lives.__

VAPALS-ELCAP is a lung-cancer screening management system:

[options="compact"]
* *VAPALS* = Veterans Affairs Partnership to increase Access to Lung Screening
* *ELCAP* = Early Lung Cancer Action Program

This is a joint project of the https://www.va.gov/[United States Department of
Veterans Affairs], http://ielcap.org/[I-ELCAP] researchers, with design, coding
and support provided by VEN and http://paraxialtech.com/[Paraxial
Technologies].

The code for this system resides in the `SAMI*` namespace in Vista. There are
several supplemental components external to the Vista codebase as well: HTML
and JavaScript files, as well as other application infrastructure. Aside from
its role in improving the lives of VA patients, VAPALS-ELCAP is also a
successful demonstration of how Vista continues to show its flexibility and
capabilities at utilizing technologies that its original creators hadn't
imagined: its primary interface is a web application that feeds information
directly into a Vista system.

This adaptation led to other incidental infrastructure issues, such as this
webpage, additional pages to supplement patch-installation instructions
(previously distributed only as text files and KID files), and developing a
flexible and unambiguous
link:{rootdir}/newsite/vista/whitepapers/versioning-202109/[modern styling for
traditional Vista version strings]. The SAMI project was our testbed for the
version schema as we developed it, and the patch files below reflect that
development. Fortunately, as of SAMI 18-13, it was finalized, and going forward
should be rigorously consistent.

To obtain releases, please visit the link:dist/[distribution page].

== Resources

[options="compact"]
* https://www.va.gov/opa/pressrel/pressrelease.cfm?id=2942[VA press release] (2017-08-31).
* https://www.va.gov/vdl/documents/Clinical/CPRS-Clinical_Reminders/pxrm_2_6_um.pdf[Clinical Reminders manual] (PDF)
