:doctitle:    VA-PALS – Projects – Vista Expertise Network
:mastimg:     aboutvista
:mastcaption: Vista consultants
:mastdesc:    Real-time patient information means real care

[role="h1"]
VA-PALS

Mission: __To increase access to safe and effective lung screening programs
that save lives.__

== New stuff

[options="compact"]
* National Implementation meeting for 09/08 added to the link:docs/meetings.html[meetings page].

== Notices

Drew Moghanaki wants to emphasize the following:

[quote]
_______________________________________________________________________________
Please refrain from posting any information about VA{nbhy}PALS in the public
domain until it undergoes review by a VA public relations director as well as
BMSF. Each of these are multi-billion dollar institutions with millions of eyes
on them. As such, the stakes are high for every word published, and there can
be unintended consequences if someone isn't happy with the way they're
represented.

This goes for any interviews, online posts, news stories, or press releases.
Also, anything that goes up on our website.

Just route to me, and I should be able to get clearance by both VA and BMSF
within 24--48h. That way, if an error goes out, they have only themselves to
blame. Not me ... which is currently the case.

Note: Our sponsor is the **Bristol-Myers Squibb Foundation**. +
Note the hyphen, as well as ``Foundation'' at the end.
_______________________________________________________________________________

== Resources

[options="compact"]
* link:docs/bmsf-proposal-2017/[The original proposal].
* link:docs/contacts.html[Contact list].
* https://www.va.gov/opa/pressrel/pressrelease.cfm?id=2942[VA press release] (2017-08-31).
* https://www.osehra.org/post/osehra-support-va-pals-open-source-project[OSEHRA press release] (2017-09-08).

* https://www.osehra.org/post/va-pals-project-overview[VA-PALS project
  overview seminar] (2017-09-17);
  https://www.osehra.org/sites/default/files/20170919_VA-PALSWebinar%20%281%29.pptx[PowerPoint
  presentation download].

=== Slideshows

[options="compact"]
* link:docs/ch-aj-talk-2017-07-18/[Slideshow]: This is the slideshow that
  accompanied a talk presented on 2017-07-18 by Artit Jirapatnakil and
  Claudia Henschke.
* link:docs/sec-1-sc-training-2013-updated/[Slideshow]: This is the slideshow that
  accompanied training on the I-ELCAP study coordinator program presented in
  2013.
* link:docs/login-page-mini-presentation/[Slideshow]: This is a minipresentation on
  a few of the pages in the I{nbhy}ELCAP system (2017-08-08).

=== Project development

[options="compact"]
* https://www.va.gov/vdl/documents/Clinical/CPRS-Clinical_Reminders/pxrm_2_6_um.pdf[Clinical Reminders manual] (PDF)
* link:docs/va-facility-alpha-codes.html[List of VA facility alpha codes] (updated 2017-08-09).
* link:docs/using-avicenna.html[Using Avicenna] (our development server)
* link:docs/rick-and-domenic-q-and-a.html[A Q&A session between Rick and Domenic on the VA{nbhy}PALS project].
* https://www.dropbox.com/l/scl/AACw0eaDZrZQQlhbN77ukeNN2sbXlfraAqg[Dropbox folder for VA-PALS].
* link:docs/meetings.html[Meetings page] (I'm starting to put all Laura's minutes and action items here).
* link:routines/[The ††**routines**†† directory]
* link:docs/elcap-forms/[ELCAP forms]

== Glossary

* **I{nbhy}ELCAP:** International Early Lung Cancer Action Program.

