#!/usr/bin/env bash
#---------------------------------------------------------------------------
# Copyright 2011-2012 The Open Source Electronic Health Record Agent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#---------------------------------------------------------------------------

# init script for QEWD

# Debian LSB info
### BEGIN INIT INFO
# Provides:          foiavista-qewd
# Required-Start:    $remote_fs $syslog $foiavista
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start QEWD for VistA at boot time
# Description:       Starts/Stops QEWD services for VistA.
### END INIT INFO

# Make sure we are root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# Setup environment variables
source /home/osehra/etc/env.conf

# Start QEWD background tasks
start() {
    # Start QEWD
    echo "Starting QEWD"
    su osehra -c "source /home/osehra/etc/env.conf && cd /home/osehra/qewd && pm2 start qewd.js"
}

# Stop EWD.js background tasks
stop() {
    # Stop QEWD
    echo "Stopping QEWD"
    su osehra -c "source /home/osehra/etc/env.conf && cd /home/osehra/qewd && pm2 kill"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 5
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
