== Help Text for VA-ELCAP Forms

=== Screening Intake Form

==== General Form Help

This form is created each time the coordinator receives an inquiry regarding
the ELCAP study. Create by clicking the ``Request New Case'' button on the
ICScreen database home page. A temporary ID is assigned for each new case
requested. The study coordinator changes this temporary ID into a permanent ID
once the patient has visited for their study appointment and background data
and CT scan is obtained.

* As described before, this form is used for all enrollee's demographic
  data. All fields must be filled out completely.

* An intake form is generated for every call received for the ELCAP study--even
  when the potential enrollee does not qualify.

** If the potential enrollee does not qualify, the ``No'' button next to
   ``Research Protocol?'' is clicked. The coordinator will then type some
   information into the ``Additional information'' comments box as to why the
   caller did not qualify.

** If the potential enrollee does meet the qualifications, the ``Yes'' button
   next to ``Research Protocol?'' is clicked.

* **Please note:** These fields must be entered on the intake form _prior_ to
  appointment:

[options="compact"]
** Patient first/last name 
** Date of exam/appointment 
** Research protocol = ``y'' if they qualify, ``n'' if they do not qualify 
** Patient street address, apartment number, county, city, state, zip code, country 
** Patient home and work phone numbers 
** Physician's first and last name and phone number 
** Date of birth 
** Parents first names (needed for registration) 
** Qualify yes/no and reason 

* All the information needed to pre-register patients for their appointments
  should be entered on this form. Depending on your institution's policies:
  schedules with new patients should be submitted for obtaining medical records
  numbers and pre-registration a week in advance.

* A temporary study ID ``TM0000'' will be automatically assigned when this
  information is obtained. After the patient's background information is taken
  on their day of appointment, a new permanent study ID will be assigned
  chronologically using a unique institution identifier followed by the
  chronological number. For example, Weill Cornell's Study IDs start with:
  AC0001, AC0002, AC0003, etc. __Do not skip study IDs; go in order as you
  interview the subjects.__

* The following information must be included on the intake form before scheduling:

[options="compact"]
** Patient first/last name 
** Address 
** Phone numbers 
** Date of exam 
** Medical record number (if available) 
** Physician's name and phone number 
** Parents' first names (for registration) 

* There is a scheduling function in the data system which takes all the
  information (demographics) and prepares it in a format for the hospital (CT)
  registration personnel and for study coordinators to use. For more
  information on the scheduling system, click here

**The following information is critical and is required on the Intake Form. It
can be obtained prior to, during, or following the Study Enrollee's
appointment.**

* Physician Information:

** A Sponsoring Physician (usually the patient's primary care MD) must be given
   for each patient. The physician's address, phone number and fax number must
   all be entered into the intake data form for several reasons.

** First, the reports must be sent to a doctor involved in the enrollee's care.

** Second, the physician information can be helpful in tracking down where a
   patient may have moved to and/or patient health status (particularly if the
   patient may have expired since their initial screening CT scan).

** Third, if follow-up procedures are necessary, the study radiologists need to
   collaborate with the enrollee's physician to ensure that they are still
   having an active role in their patient's care.

** Finally, it may be necessary to have their doctor order follow-up diagnostic
   procedures (particularly when pre-certifications are needed by certain
   insurance companies) and developing rapport with the patient's physician
   office is important in this regard.

* Next of Kin

** This information is needed mostly for when the patient cannot be found and
   needs either follow-up diagnostic procedures and/or needs to come back for
   their repeat screening CT scan.

** Need to collect the Next of Kin's name, relation and phone number.

* Comments:

** **General:** Please document all conversations with the patient, doctor,
   etc., in this area. Also when information is sent to the patient, list it
   here.

** **Scheduling Comments:** Please enter info when you call to schedule
   appointments in this section. It will keep a log in the second box with all
   your notes on the intake form. This section is prompted for entry when you
   click on the ``schedule'' button while in ``Case Review''.

==== Help button next to “Patient Contact Information”

Use the Update button when the patient's contact information changes. It will
save a copy of the information into the Additional Patient Information and
clear the appropriate fields so that you may enter the new contact information.

==== Help button next to Physician Contact Information

Use the Update button when the physician's contact information changes.  It
will save a copy of the information into the Additional Patient Information and
clear the appropriate fields so that you may enter the new contact information.

==== Help button next to Date of Exit

The Date of Exit should be recorded for all subjects who are no longer active
in the study.  It signifies the date on which they change to a non-active
status.

==== Help button next to Correspondence

This section should be used to record correspondence or communication with the
patient or physician.  This includes the date, recipient and nature of the
communication, the date of the relevant CT exam, and the identity of the
coordinator.

=== Background Form

==== General form help

This form is used to obtain the enrollee's general medical history as well as
some familial medical history. Information is also obtained on the
participant's smoking history, quitting history, and health opinions. The
SF-12™ Health Survey is also incorporated into this form (by special permission
to use) as a tool to assess the subject's health in general (both physical and
mental).

On the date of the subject's appointment, he/she meets face to face with the
site study coordinator. During this time, the participant signs the IRB Consent
form and has an opportunity to ask questions about it. Once the consent is
signed, a unique Study ID is assigned to the subject. The subject is then
interviewed by the study coordinator using the data form which
follows. Following the face-to face interview, the study coordinator explains
when (and how) the results will be given to the participant as well as their
physician and then the subject is escorted to have their CT scan. To create a
background form:

. Search the ``Case Review'' function on the data base home page to access the
  person for which you wish to enter data. If they have already been assigned a
  Study ID, you can search for it by the ID or you may choose to search by the
  subject's last name. Either way, type in the value you wish to search, and
  click ``Request Case''.

. You may then click the option to create ``New Form''.

. When prompted, select ``Background form'' from the scroll options of forms to
  create. And then, click ``Request New Form''

. If you have already updated the Study ID on the intake form, you will notice
  that it will appear, along with the subject's last and first name, date of
  birth and medical record number (if you had entered all of these fields into
  the intake form)

Detailed help information on many of the fields in the Screening Background
form is accessible using the small yellow help buttons on the form itself.

Once all of the questions have been asked in the interview, the form can be
completed and submitted as a permanent data entry once the ``Submit Data''
button at the bottom of the form is clicked.

==== Help button next to Race

The race of the subject should be selected from one of the following:

* American Indian: A person having origins in any of the original peoples of
  North America, and who maintains cultural identification through tribal
  affiliation or community recognition.

* Alaskan Native: A person having origins in any of the indigenous peoples of
  Alaska, and who maintains cultural identification through tribal affiliation
  or community recognition.

* Asian: A person having origins in any of the original peoples original
  peoples of the Far East, Southeast Asia, or the Indian subcontinent.  This
  area includes, for example, China, India, Japan, Korea, and the Philippine
  Islands.

* Native Hawaiian or Other Pacific Islander: A person having origins in any of
  the original peoples of Hawaii or the Pacific Islands.  This area includes,
  for example, Hawaii, Polynesia, Melanesia, and Micronesia.

* Black or African American: A person having origins in any of the black racial
  groups of Africa.

* White: A person having origins in any of the original peoples of Europe,
  North Africa, or the Middle East.

* Two or more: A person self-identifying as multiracial.

* Other (specify): Any other race reported that doesn't fit the above
  categories.  If this category is chosen, a specification must be made in the
  Other (specify) field to the right of the pull-down menu.

=== CT Evaluation From

==== General form help

The CT Evaluation Form records the findings of the screening and follow-up
diagnostic CT scans. Detailed nodule information and other abnormalities found
are recorded on this form by the radiologist.

The radiologist should complete a separate CT Evaluation Form for each CT scan
performed..

If the scan was performed at an outside institution and the films or report are
submitted for interpretation, the CT Scan Performed at Outside Institution
checkbox must be checked.

TYPES OF CT EXAMS:

* Baseline - The baseline low-dose CT should always be the first CT evaluation
  for enrollment.

* Annual Repeat - Annual repeat helical chest CT performed at low dose settings
  on the anniversary date of the baseline scan.

* Follow-up (not annual repeat) - If one or more non-calcified nodules are seen
  on the screening test, the usual recommendation for follow-up is a standard
  diagnostic CT with high resolution images of the nodules. This may be either
  a limited or full diagnostic scan which does not fall within three months of
  the anniversary date of the baseline CT.
+
In each case, high-resolution CT (HRCT) of the nodules being followed will be
  made of each nodule using 1 mm slice thickness, target field of view (9.6 mm),
  obtained in a single breath hold.

* Annual Repeat Screen - If there were no clinically significant findings on
  the screening CT, then the patient is recommended to have a repeat screening
  CT in one year.

* Annual Diagnostic Follow-up - A full chest diagnostic CT scan is done one
  year following a diagnostic follow-up as recommended by the radiologist.

TO CREATE A NEW CT EVALUATION FORM (This should be done by the radiologist):

Upon entering the ELCAP data system, type the desired Study ID and click
Request Case. This brings you to the Case Review List.

From here select New Form and then choose CT Evaluation in the pull-down menu.

Click on Request New Form. The new form will have patient's name, study ID, and
medical record number which are copied from the intake form.

NODULE DETAILS

Total Number of Non-Calcified Nodules - This total refers to the total number
of non-calcified nodules seen on that CT for which you are filling out a form.

Total Number of Nodules (Overall) - This total refers to the number of nodules
seen in general throughout all exams. In other words, if a nodule is not
visualized on the particular limited diagnostic CT for which you are filling
out a form, it still must be counted.

Nodule ID - Each nodule is given a name or nodule ID which remains the same
throughout. Therefore, no other nodule can have the same nodule ID.

* Once a nodule has been assigned an ID, that nodule ID must be used on all
  subsequent exams.

Is it new? - A pull-down menu allows us to note whether a nodule is newly seen,
previously seen, or seen in retrospect, as well as any change in size.

Most Likely Location - If a nodule location is different from where it was
described to be previously, do not go back and change the location on the
previous exams but make sure to make a note of the previously mentioned
location in the Comment field (see description below).

Distance from the costal pleura - The shortest distance from the nodule to the
costal pleura should be measured in millimeters.

Length and Width - The largest dimension of the nodule is always the
Length. The maximum width is the largest perpendicular dimension to the length
of the nodule. The unit of measurement is always millimeters.

Nodule Consistency - Nodules may be classified into three types by attenuation
characteristics:

* solid - nodule is uniformly solid in appearance

* non-solid - nodule is uniformly non-solid (except for blood vessels) in
  appearance

* part-solid - nodule has both solid and non-solid components

Smooth Edges - Indicate whether the nodule has a smooth-appearing margin.

Calcifications c/w Benignity - Indicate whether the nodule has regions of
calcification that are consistent with benignity. Nodules that are considered
calcified or probably calcified (``?''), are NOT COUNTED toward the total
number of non-calcified nodules, only toward the total number of nodules.

Spiculations / Pleural Tags - Indicate whether the nodule has spiculations or
``pleural tags'' connecting it to the pleural surface.

Nodule seen in series - Indicate the CT series number in which the nodule
appears.

Nodule seen in images - Indicate the CT image numbers in which the nodule
appears.

Nodule Status - A pull-down menu allows us to choose the status of the
nodule. We can select among many options including whether the status is
unknown, benign, or malignant as well as the method of diagnosis.

There are a number of automatic entries for the Nodule Status field.

If nodule calcifications are seen (``yes'' is selected for Calcifications),
``benign (Ca++)'' will automatically appear under Nodule Status.

When ``?'' is selected under Calcifications, Nodule Status will read ``prob
benign, prob Ca++'' (probably benign, probably calcified).

If the nodule is ``prev seen, resolved,'' as noted in the ``Is it new'' field,
then Nodule Status will automatically read ``resolved.''

When ``prev seen, resected'' is selected for ``Is it new,''
``Resected-malignant'' appears under Nodule Status.

If under ``Is it new'' it reads ``not included in scan,'' Nodule Status will
also read ``not included in scan.''

These automatic entries help to maintain a level of consistency for data entry
across institutions.

Action - This field becomes very important when different nodules require
different follow-up. A pull-down menu allows a choice among nine different
follow-up actions - ``repeat SCT'' (repeat screening CT), ``f/u Dx CT''
(follow-up Diagnostic CT), ``Abx + f/u Dx CT'' (Antibiotic + follow-up
Diagnostic CT), ``biopsy'', ``bronchoscopy'', or ``resection''.

Comment - This field is for additional comments about the nodule. If a
previously seen nodule is found to be something other than a nodule, note it
here.

Pathologic Diagnosis - If a biopsy was previously performed, the diagnosis was
chosen from a pull-down menu on the Biopsy form. When CT evaluation forms are
created after the biopsy was done, the ``Pathologic Diagnosis'' selected on the
Biopsy Form is transferred onto the new CT evaluation Form. Once a diagnosis
has been assigned on the Biopsy Form and it pops up on the CT evaluation form,
it CANNOT be changed.

ORDER OF NODULES

The order of nodules is important and is established by the baseline screening
CT. Nodules should be listed in the following order:

. non-calcified nodules by size beginning with the largest

. calcified and probably calcified nodules by size beginning with the largest

The largest non-calcified nodule seen on baseline is Nodule 1. If there is no
non-calcified nodule seen on the screening CT, then the largest calcified is
Nodule 1. It is important to remember that THE ORDER OF NODULES REMAINS
CONSISTENT THROUGHOUT ALL CT SCANS. Therefore, any newly seen non-calcified
nodule, no matter how large, should come after those seen on the baseline
screening CT.

The study coordinator must check to make certain that the order of nodules is
correct for each CT scan.

OTHER ABNORMALITIES (not nodules)

There is a set of fields for abnormalities other than nodules that are commonly
identified on chest CT. The radiologist should note each abnormality in the
report.

If there is any additional abnormality for which there is no specific field, it
should be noted under ``Other Abnormalities''.

FOLLOW-UP

This section refers to the most immediate action that needs to be taken with
respect to the patient, including any nodules or other abnormalities.

It is important that on subsequent forms, the physician take care to update the
status and action fields corresponding to each abnormality and select the most
important follow-up of the remaining recommended actions.

IMPRESSION

The impression refers to the findings on the nodules and other abnormalities
previously mentioned.

ADDITIONAL NOTES

Detailed help information on many of the fields in the CT Evalutation form is
accessible using the small yellow help buttons on the form itself.

Once a form is completed, click ``Submit Data'' at the bottom of the form. The
system will not allow a form to be submitted unless all required fields have
been completed.

Note: You MUST CLICK ``Submit Data'' each time a form is updated.

OTHER SYSTEM FEATURES RELATED TO CT EVALUATION FORMS

Final Reading - After the site reading and central reading are completed, the
site reader must designate one of the two reports as the final
reading. Alternatively, the site reader may create a third CT evaluation form
to serve as the final reading. In any case, the form that is to represent the
final reading must have this checkbox checked.

Report Feature - On the Case Review page, next to each CT Evaluation form,
there is a ``Report'' button. This option generates a report from the CT
Evaluation form. This radiologist may use this report to facilitate their
dictation.
