:doctitle:    VA-PALS – Projects – Vista Expertise Network
:mastimg:     aboutvista
:mastcaption: Vista consultants
:mastdesc:    Real-time patient information means real care

== VA-PALS

Mission: __To increase access to safe and effective lung screening programs
that save lives.__

Drew Moghanaki wants to emphasize the following:

[quote]
_______________________________________________________________________________
Please refrain from posting any information about VA{nbhy}PALS in the public
domain until it undergoes review by a VA public relations director as well as
BMSF. Each of these are multi-billion dollar institutions with millions of eyes
on them. As such, the stakes are high for every word published, and there can
be unintended consequences if someone isn't happy with the way they're
represented.

This goes for any interviews, online posts, news stories, or press releases.
Also, anything that goes up on our website.

Just route to me, and I should be able to get clearance by both VA and BMSF
within 24--48h. That way, if an error goes out, they have only themselves to
blame. Not me ... which is currently the case.

Note: Our sponsor is the **Bristol-Myers Squibb Foundation**. +
Note the hyphen, as well as ``Foundation'' at the end.
_______________________________________________________________________________

=== Resources

Note: Help text for VA-ELCAP added 2017-10-11.

[options="compact"]
* link:bmsf-proposal-2017/[The original proposal]
* https://www.va.gov/vdl/documents/Clinical/CPRS-Clinical_Reminders/pxrm_2_6_um.pdf[Clinical Reminders manual] (PDF)
* link:elcap-forms/[ELCAP forms]
* link:ch-aj-talk-2017-07-18/[Slideshow]: This is the slideshow that
  accompanied a talk presented on 2017-07-18 by Artit Jirapatnakil and
  Claudia Henschke.
* link:sec-1-sc-training-2013-updated/[Slideshow]: This is the slideshow that
  accompanied training on the I-ELCAP study coordinator program presented in
  2013.
* link:login-page-mini-presentation/[Slideshow]: This is a minipresentation on
  a few of the pages in the I{nbhy}ELCAP system (2017-08-08).
* link:va-facility-alpha-codes.html[List of VA facility alpha codes]: Updated
  2017-08-09.
* link:using-avicenna.html[Using Avicenna] (our development server)
* link:rick-and-domenic-q-and-a.html[A Q&A session between Rick and Domenic on
the VA{nbhy}PALS project].
* https://www.dropbox.com/l/scl/AACw0eaDZrZQQlhbN77ukeNN2sbXlfraAqg[Dropbox folder for VA-PALS].
* link:meetings.html[Meetings page] (I'm starting to put all Laura's minutes and action items here).
* link:help-text-for-va-elcap.html[Help text for VA-ELCAP].

=== Glossary

* **I{nbhy}ELCAP:** International Early Lung Cancer Action Program.

=== Forms

These now have their link:elcap-forms/[own page].

=== Contacts

<<abbaszadegan,Hamed Abbaszadegan>>
  <hamed.abbaszadegan@va.gov> +
<<aguayo,Sam Aguayo>>
  <samuel.aguayo@va.gov> +
<<avila,Ricardo Avila>>
  <rick.avila@paraxialtech.com> +
<<carlson,Alexis Carlson>>
  <alexis.carlson@vistaexpertise.net> +
<<cartwright,Laura Cartwright>>
  <cartwrightvapals@gmail.com> +
<<coupaud,Paul Coupaud>>
  <paul.coupaud@va.gov> +
<<dorfer,Cindy Dorfer>>
  <cynthia.dorfner@va.gov> +
<<henschke,Claudia Henschke, PhD, MD>>
  <claudia.henschke@mountsinai.org> +
<<ice,Kathy Ice>>
  <kathy.ice@vistaexpertise.net> +
<<jirapatnakul,Artit Jirapatnakul>>
  <artit.jirapatnakul@mountsinai.org> +
<<lilly,George Lilly>>
  <george.lilly@vistaexpertise.net> +
<<marshall,Frederick Marshall>>
  <rick.marshall@vistaexpertise.net> +
<<max,Daniel Max>>
  <daniel.max@mountsinai.org> +
<<mcglothlen,Ken McGlothlen>>
  <ken.mcglothlen@vistaexpertise.net> +
<<moghanaki,Drew Moghanaki>>
  <drew.moghanaki@gmail.com> +
<<morales,Providencia Morales>>
  <Providencia.Morales@va.gov> +
<<permana,Paska Permana>>
  <paska.permana@va.gov> +
<<prado,Nickolas Prado>>
  <nickolas.prado@mountsinai.org> +
<<reccoppa,Vivian P. Reccoppa>>
  <vivian.reccoppa@mountsinai.org> +
<<rubacky,Maryanne Rubacky>>
  <maryanne.rubacky@mountsinai.org> +
<<williams,Angel Williams>>
  <Angel.Williams@mountsinai.org> +
<<yankelevitz,David Yankelevitz>>
  <david.yankelevitz@mountsinai.org> +
<<yaw,Linda Yaw>>
  <linda.yaw@vistaexpertise.net> +
<<yip,Rowena Yip>>
  <rowena.yip@mountsinai.org>

[[abbaszadegan]]
**Hamed Abbaszadegan, MD, MBA, FACP** +
Chief Health Informatics Officer +
Phoenix VA Health Care System +
Assistant Professor of Internal Medicine & Biomedical Informatics +
University of Arizona College of Medicine--Phoenix +
hamed.abbaszadegan@va.gov

[[aguayo]]
**Samuel M Aguayo** +
samuel.aguayo@va.gov

[[avila]]
**Ricardo Avila** +
Paraxial Technologies +
C: 518-210-4194 +
rick.avila@paraxialtech.com +
rick.avila@gmail.com

[[carlson]]
**Alexis Carlson** +
Software Developer +
C: 206-601-8728 +
alexis.carlson@vistaexpertise.com

[[cartwright]]
**Laura Cartwright, Ph.D., MPH** +
Senior Program Manager +
C: 703-371-2071 +
cartwrightvapals@gmail.com

[[coupaud]] 
**Paul Coupaud, Ed.D., USAF ret.** +
Chief, Communication Dept. / PAO +
Phoenix VA Health Care System +
P: 602-222-2667 +
paul.coupaud@va.gov

[[dorfer]]
**Cindy Dorfer** +
Chief of Medical Media +
cynthia.dorfer@va.gov

[[henschke]]
**Claudia Henschke** +
C: 646-322-5555 +
claudia.henschke@mountsinai.org +
cihenschke@gmail.com

[[ice]]
**Kathy Ice** +
Documenter +
kathy.ice@vistaexpertise.net

[[jirapatnakul]]
**Artit Jirapatnakul** +
Systems Programmer (database) +
C: 484-995-7456 +
artit.jirapatnakul@mountsinai.org

[[lilly]]
**George Lilly** +
Software Developer/Team Lead +
Vista Expertise Network +
C: 917-723-8358 +
george.lilly@vistaexpertise.net

[[marshall]]
**Frederick D. S. Marshall** +
Executive Director +
Vista Expertise Network +
819 N 49th St, Ste 203 +
Seattle WA{ensp}98103-6576 +
C: 206-465-5765 +
rick.marshall@vistaexpertise.net

[[max]]
**Daniel Max** +
Systems Programmer (database) +
daniel.max@mountsinai.org

[[mcglothlen]]
**Ken McGlothlen** + 
ken.mcglothlen@vistaexpertise.net

[[moghanaki]]
**Drew Moghanaki** +
C: 804-306-9045 +
drew.moghanaki@gmail.com 

[[morales]]
**Providencia Morales** +
Providencia.Morales@va.gov

[[permana]]
**Paska Permana** +
paska.permana@va.gov

[[prado]]
**Nickolas Prado** +
nickolas.prado@mountsinai.org

[[reccoppa]]
**Vivian P. Reccoppa** +
Administrative Director +
Early Lung and Cardiac Action Program +
Icahn School of Medicine at Mount Sinai +
One Gustave L Levy Place, Box 1234 +
New York NY{ensp}10029 +
P: 212-241-4324 +
C: 646-647-7771 +
F: 212-241-9655 +
vivian.reccoppa@mountsinai.org

[[rubacky]]
**Maryanne Rubacky** +
maryanne.rubacky@mountsinai.org

[[williams]]
**Angel Williams** +
C: 347-237-0046 +
Angel.Williams@mountsinai.org

[[yankelevitz]]
**David Yankelevitz** +
C: 646-322-4555 +
david.yankelevitz@mountsinai.org 

[[yaw]]
**Linda M. R. Yaw** +
Director of Operations +
Vista Expertise Network +
819 N 49th St, Ste 203 +
Seattle WA{ensp}98103-6576 +
C: 425-241-6473 +
linda.yaw@vistaexpertise.net

[[yip]]
**Rowena Yip** +
Statistician +
C: 646-226-9962 +
rowena.yip@mountsinai.org
