:doctitle:    VA-PALS – Projects – Vista Expertise Network
:mastimg:     aboutvista
:mastcaption: Vista consultants
:mastdesc:    Real-time patient information means real care

== VA-PALS

Mission: __To increase access to safe and effective lung screening programs
that save lives.__

[options="compact"]
* link:bmsf-proposal-2017/[The original proposal]
* https://www.va.gov/vdl/documents/Clinical/CPRS-Clinical_Reminders/pxrm_2_6_um.pdf[Clinical Reminders manual] (PDF)
* link:elcap-forms/[ELCAP forms]
* link:ch-aj-talk-2017-07-18/[Slideshow]: This is the slideshow that
  accompanied a talk presented on 2017-07-18 by Artit Jirapatnakil and
  Claudia Henschke.
* link:sec-1-sc-training-2013-updated/[Slideshow]: This is the slideshow that
  accompanied training on the I-ELCAP study coordinator program presented in
  2013.
* link:login-page-mini-presentation/[Slideshow]: This is a minipresentation on
  a few of the pages in the I{nbhy}ELCAP system (2017-08-08).
* link:va-facility-alpha-codes.html[List of VA facility alpha codes]: Updated
  2017-08-09.

=== Sample JSON files

These are samples provided by ELCAP in JSON form. They currently reside on
Avicenna (VEN's development server for VA{nbhy}PALS).

[options="compact"]
* http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/bxform.json[Biopsy form]
* CT Evaluation forms:
http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/ceform.json[sample{nbsp}1],
http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/ceform2.json[sample{nbsp}2],
http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/ceform3.json[sample{nbsp}3].
* http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/fuform.json[Followup form]
* http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/ptform.json[PET Evaluation form]
* http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/rbform.json[]
* http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/sbform.json[Background form]
* http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/siform.json[Intake form]

=== Sample stuff

* link:elcap-forms/elcap-background-form.html[Background form] (in progress)

=== Contacts

Ricardo Avila <rick.avila@paraxialtech.com> +
Alexis Carlson <alexis.carlson@vistaexpertise.net> +
Laura Cartwright <cartwrightvapals@gmail.com> +
Claudia Henschke <claudia.henschke@mountsinai.org> +
Kathy Ice <kathy.ice@vistaexpertise.net> +
Artit Jirapatnakul <artit.jirapatnakul@mountsinai.org> +
George Lilly <george.lilly@vistaexpertise.net> +
<<marshall,Frederick Marshall>>
  <rick.marshall@vistaexpertise.net> +
Daniel Max <daniel.max@mountsinai.org> +
Ken McGlothlen <ken.mcglothlen@vistaexpertise.net> +
Drew Moghanaki <drew.moghanaki@gmail.com> +
Nickolas Prado <nickolas.prado@mountsinai.org> +
<<reccoppa,Vivian P. Reccoppa>>
  <vivian.reccoppa@mountsinai.org> +
Maryanne Rubacky <maryanne.rubacky@mountsinai.org> +
David Yankelevitz <david.yankelevitz@mountsinai.org> +
<<yaw,Linda Yaw>>
  <linda.yaw@vistaexpertise.net> +
Rowena Yip <rowena.yip@mountsinai.org>

[[marshall]]
**Frederick D. S. Marshall** +
Executive Director +
Vista Expertise Network +
819 N 49th St, Ste 203 +
Seattle WA{ensp}98103-6576 +
P: 206-632-0166 +
rick.marshall@vistaexpertise.net

[[reccoppa]]
**Vivian P. Reccoppa** +
Administrative Director +
Early Lung and Cardiac Action Program +
Icahn School of Medicine at Mount Sinai +
One Gustave L Levy Place, Box 1234 +
New York NY{ensp}10029 +
P: 212-241-4324 +
C: 646-647-7771 +
F: 212-241-9655 +
vivian.reccoppa@mountsinai.org

[[yaw]]
**Linda M. R. Yaw** +
Director of Operations +
Vista Expertise Network +
819 N 49th St, Ste 203 +
Seattle WA{ensp}98103-6576 +
C: 425-241-6473 +
linda.yaw@vistaexpertise.net

