:doctitle:    VA-PALS – Projects – Vista Expertise Network
:mastimg:     aboutvista
:mastcaption: Vista consultants
:mastdesc:    Real-time patient information means real care

== VA-PALS

Mission: __To increase access to safe and effective lung screening programs
that save lives.__

[options="compact"]
* link:bmsf-proposal-2017/[The original proposal]
* https://www.va.gov/vdl/documents/Clinical/CPRS-Clinical_Reminders/pxrm_2_6_um.pdf[Clinical Reminders manual] (PDF)
* link:elcap-forms/[ELCAP forms]
* link:ch-aj-talk-2017-07-18/[Slideshow]: This is the slideshow that
  accompanied a talk presented on 2017-07-18 by Artit Jirapatnakil and
  Claudia Henschke.
* link:sec-1-sc-training-2013-updated/[Slideshow]: This is the slideshow that
  accompanied training on the I-ELCAP study coordinator program presented in
  2013.
* link:login-page-mini-presentation/[Slideshow]: This is a minipresentation on
  a few of the pages in the I{nbhy}ELCAP system (2017-08-08).
* link:va-facility-alpha-codes.html[List of VA facility alpha codes]: Updated
  2017-08-09.
* link:using-avicenna.html[Using Avicenna] (our development server)

=== Glossary

* **I{nbhy}ELCAP:** International Early Lung Cancer Action Program.

=== Forms

JSON samples: These are provided by ELCAP, and currently reside on
Avicenna (VEN's development server for VA{nbhy}PALS).

[options="compact"]
* Biopsy form (††bxform††):
** link:elcap-forms/elcap-biopsy-form.pdf[Original PDF]
** http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/bxform.json[JSON sample]
* CT Evaluation form (††ceform††):
** link:elcap-forms/elcap-ct-evaluation-form.pdf[Original PDF]
** JSON samples: http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/ceform.json[sample{nbsp}1],
   http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/ceform2.json[sample{nbsp}2],
   http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/ceform3.json[sample{nbsp}3].
* Followup form (††fuform††):
** link:elcap-forms/elcap-follow-up-form.pdf[Original PDF]
** http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/fuform.json[JSON sample]
* PET Evaluation form (††ptform††):
** link:elcap-forms/elcap-pet-scan-form.pdf[Original PDF]
** http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/ptform.json[JSON sample]
* Intervention form (††rbform††):
** link:elcap-forms/elcap-intervention-form.pdf[Original PDF]
** http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/rbform.json[JSON sample]
* Background form (††sbform††):
** link:elcap-forms/elcap-background-form.pdf[Original PDF]
** http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/sbform.json[JSON sample]
** link:elcap-forms/elcap-background-form.html[Draft in progress]
** link:elcap-forms/elcap-background-form-2.html[Proposed revision in progress]
** link:elcap-forms/elcap-background-form-dd.html[Data dictionary, compiled from the spreadsheet]
* Intake form (††siform††):
** link:elcap-forms/elcap-intake-form.pdf[Original PDF]
** http://avicenna.vistaexpertise.net:9080/filesystem/sample-json/siform.json[JSON sample]

=== Contacts

<<abbaszadegan,Hamed Abbaszadegan>>
  <hamed.abbaszadegan@va.gov> +
<<aguayo,Sam Aguayo>>
  <samuel.aguayo@va.gov> +
<<avila,Ricardo Avila>>
  <rick.avila@paraxialtech.com> +
<<carlson,Alexis Carlson>>
  <alexis.carlson@vistaexpertise.net> +
<<cartwright,Laura Cartwright>>
  <cartwrightvapals@gmail.com> +
<<coupaud,Paul Coupaud>>
  <paul.coupaud@va.gov> +
<<dorfer,Cindy Dorfer>>
  <cynthia.dorfner@va.gov> +
<<henschke,Claudia Henschke, PhD, MD>>
  <claudia.henschke@mountsinai.org> +
<<ice,Kathy Ice>>
  <kathy.ice@vistaexpertise.net> +
<<jirapatnakul,Artit Jirapatnakul>>
  <artit.jirapatnakul@mountsinai.org> +
<<lilly,George Lilly>>
  <george.lilly@vistaexpertise.net> +
<<marshall,Frederick Marshall>>
  <rick.marshall@vistaexpertise.net> +
<<max,Daniel Max>>
  <daniel.max@mountsinai.org> +
<<mcglothlen,Ken McGlothlen>>
  <ken.mcglothlen@vistaexpertise.net> +
<<moghanaki,Drew Moghanaki>>
  <drew.moghanaki@gmail.com> +
<<morales,Providencia Morales>>
  <Providencia.Morales@va.gov> +
<<permana,Paska Permana>>
  <paska.permana@va.gov> +
<<prado,Nickolas Prado>>
  <nickolas.prado@mountsinai.org> +
<<reccoppa,Vivian P. Reccoppa>>
  <vivian.reccoppa@mountsinai.org> +
<<rubacky,Maryanne Rubacky>>
  <maryanne.rubacky@mountsinai.org> +
<<williams,Angel Williams>>
  <Angel.Williams@mountsinai.org> +
<<yankelevitz,David Yankelevitz>>
  <david.yankelevitz@mountsinai.org> +
<<yaw,Linda Yaw>>
  <linda.yaw@vistaexpertise.net> +
<<yip,Rowena Yip>>
  <rowena.yip@mountsinai.org>

[[abbaszadegan]]
**Hamed Abbaszadegan, MD, MBA, FACP** +
Chief Health Informatics Officer +
Phoenix VA Health Care System +
Assistant Professor of Internal Medicine & Biomedical Informatics +
University of Arizona College of Medicine--Phoenix +
hamed.abbaszadegan@va.gov

[[aguayo]]
**Samuel M Aguayo** +
samuel.aguayo@va.gov

[[avila]]
**Ricardo Avila** +
Paraxial Technologies +
C: 518-210-4194 +
rick.avila@paraxialtech.com +
rick.avila@gmail.com

[[carlson]]
**Alexis Carlson** +
Software Developer +
C: 206-601-8728 +
alexis.carlson@vistaexpertise.com

[[cartwright]]
**Laura Cartwright** +
C: 703-371-2071 +
cartwrightvapals@gmail.com

[[coupaud]] 
**Paul Coupaud, Ed.D., USAF ret.** +
Chief, Communication Dept. / PAO +
Phoenix VA Health Care System +
P: 602-222-2667 +
paul.coupaud@va.gov

[[dorfer]]
**Cindy Dorfer** +
Chief of Medical Media +
cynthia.dorfer@va.gov

[[henschke]]
**Claudia Henschke** +
C: 646-322-5555 +
claudia.henschke@mountsinai.org +
cihenschke@gmail.com

[[ice]]
**Kathy Ice** +
Documenter +
kathy.ice@vistaexpertise.net

[[jirapatnakul]]
**Artit Jirapatnakul** +
Systems Programmer (database) +
C: 484-995-7456 +
artit.jirapatnakul@mountsinai.org

[[lilly]]
**George Lilly** +
Software Developer/Team Lead +
Vista Expertise Network +
C: 917-723-8358 +
george.lilly@vistaexpertise.net

[[marshall]]
**Frederick D. S. Marshall** +
Executive Director +
Vista Expertise Network +
819 N 49th St, Ste 203 +
Seattle WA{ensp}98103-6576 +
C: 206-465-5765 +
rick.marshall@vistaexpertise.net

[[max]]
**Daniel Max** +
Systems Programmer (database) +
daniel.max@mountsinai.org

[[mcglothlen]]
**Ken McGlothlen** + 
ken.mcglothlen@vistaexpertise.net

[[moghanaki]]
**Drew Moghanaki** +
C: 804-306-9045 +
drew.moghanaki@gmail.com 

[[morales]]
**Providencia Morales** +
Providencia.Morales@va.gov

[[permana]]
**Paska Permana** +
paska.permana@va.gov

[[prado]]
**Nickolas Prado** +
nickolas.prado@mountsinai.org

[[reccoppa]]
**Vivian P. Reccoppa** +
Administrative Director +
Early Lung and Cardiac Action Program +
Icahn School of Medicine at Mount Sinai +
One Gustave L Levy Place, Box 1234 +
New York NY{ensp}10029 +
P: 212-241-4324 +
C: 646-647-7771 +
F: 212-241-9655 +
vivian.reccoppa@mountsinai.org

[[rubacky]]
**Maryanne Rubacky** +
maryanne.rubacky@mountsinai.org

[[williams]]
**Angel Williams** +
C: 347-237-0046 +
Angel.Williams@mountsinai.org

[[yankelevitz]]
**David Yankelevitz** +
C: 646-322-4555 +
david.yankelevitz@mountsinai.org 

[[yaw]]
**Linda M. R. Yaw** +
Director of Operations +
Vista Expertise Network +
819 N 49th St, Ste 203 +
Seattle WA{ensp}98103-6576 +
C: 425-241-6473 +
linda.yaw@vistaexpertise.net

[[yip]]
**Rowena Yip** +
Statistician +
C: 646-226-9962 +
rowena.yip@mountsinai.org
