:doctitle:    VA-PALS – Projects – Vista Expertise Network

== VA-PALS

Mission: __To increase access to safe and effective lung screening programs
that save lives.__

Drew Moghanaki wants to emphasize the following:

[quote]
_______________________________________________________________________________
Please refrain from posting any information about VA{nbhy}PALS in the public
domain until it undergoes review by a VA public relations director as well as
BMSF. Each of these are multi-billion dollar institutions with millions of eyes
on them. As such, the stakes are high for every word published, and there can
be unintended consequences if someone isn't happy with the way they're
represented.

This goes for any interviews, online posts, news stories, or press releases.
Also, anything that goes up on our website.

Just route to me, and I should be able to get clearance by both VA and BMSF
within 24--48h. That way, if an error goes out, they have only themselves to
blame. Not me ... which is currently the case.

Note: Our sponsor is the **Bristol-Myers Squibb Foundation**. +
Note the hyphen, as well as ``Foundation'' at the end.
_______________________________________________________________________________

=== Resources

[options="compact"]
* https://www.va.gov/vdl/documents/Clinical/CPRS-Clinical_Reminders/pxrm_2_6_um.pdf[Clinical Reminders manual] (PDF)
* link:va-facility-alpha-codes.html[List of VA facility alpha codes]: Updated
  2017-08-09.
* link:using-avicenna.html[Using Avicenna] (our development server)
* link:rick-and-domenic-q-and-a.html[A Q&A session between Rick and Domenic on
  the VA{nbhy}PALS project].
* link:meetings.html[Meetings page] (I'm starting to put all Laura's minutes and action items here).
* link:help-text-for-va-elcap.html[Help text for VA-ELCAP].

=== Glossary

* **I{nbhy}ELCAP:** International Early Lung Cancer Action Program.

