:doctitle:    VA-PALS – Projects – Vista Expertise Network
:mastimg:     aboutvista
:mastcaption: Vista consultants
:mastdesc:    Real-time patient information means real care

== VA-PALS

Mission: __To increase access to safe and effective lung screening programs
that save lives.__

* link:bmsf-proposal-2017/[The original proposal]
* https://www.va.gov/vdl/documents/Clinical/CPRS-Clinical_Reminders/pxrm_2_6_um.pdf[Clinical Reminders manual] (PDF)

=== Contacts

Some people for the Roster

Nickolas Prado nickolas.prado@mountsinai.org +
Rowena Yip rowena.yip@mountsinai.org +
Daniel Max daniel.max@mountsinai.org +
Maryanne Rubacky maryanne.rubacky@mountsinai.org +
Artit Jirapatnakul artit.jirapatnakul@mountsinai.org +
Claudia Henschke claudia.henschke@mountsinai.org +
David Yankelevitz david.yankelevitz@mountsinai.org +
Vivian P. Reccoppa vivian.reccoppa@mountsinai.org +
Laura Cartwright cartwrightvapals@gmail.com +
Ricardo Avila rick.avila@paraxialtech.com +
Drew Moghanaki drew.moghanaki@gmail.com +
Alexis Carlson alexis.carlson@vistsaexpertise.net +
Kathy Ice kathy.ice@vistaexpertise.net +
Ken McGlothlen ken.mcglothlen@vistaexpertise.net +
George Lilly george.lilly@vistaexpertise.net +
Linda Yaw linda.yaw@vistaexpertise.net +
Frederick Marshall rick.marshall@vistaexpertise.net +

Here's fuller contact info for Vivian Reccoppa:

Vivian P Reccoppa +
Administrative Director +
Early Lung and Cardiac Action Program +
Icahn School of Medicine at Mount Sinai +
One Gustave L Levy Place, Box 1234 +
New York, NY 10029 +
P: 212-241-4324 +
C: 646-647-7771 +
F: 212-241-9655 +
vivian.reccoppa@mountsinai.org